spring.application.name=SpringOauth2Client

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

spring.security.oauth2.client.registration.github.clientId=xyz
spring.security.oauth2.client.registration.github.clientSecret=xyz

spring.security.oauth2.client.registration.google.clientId=xyz
spring.security.oauth2.client.registration.google.clientSecret=xyz
