spring.application.name=SpringCamelGateway

## Logging
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n
logging.level.org.keycloak=DEBUG
logging.level.org.springframework.security=DEBUG

# URLs múltiples para mostrar AMBAS APIs en Swagger U
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Configuración adicional de SpringDoc
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.displayRequestDuration=true

# ===== CONFIGURACIÓN DE CAMEL =====
# Configuración de Camel Servlet
camel.servlet.mapping.context-path=/camel/api/*
camel.rest.component=servlet
camel.rest.data-format-property.prettyPrint=true
camel.rest.binding-mode=json
camel.rest.enable-cors=true

# Configuración general de Camel
camel.springboot.main-run-controller=true

# ===== CONFIGURACIÓN DE LOGGING =====
logging.level.ec.redcode.net=DEBUG
logging.level.org.apache.camel=INFO