spring.application.name=camel-springboot-rest

# Configuración del servidor
server.port=8080

# Configuración de Camel
#camel.springboot.name=CamelRestSwaggerDemo
camel.servlet.mapping.context-path=/api/*

# Configuración de Swagger UI
camel.rest.api-context-path=/api-doc
#camel.rest.api-context-listing.enabled=true
camel.rest.enable-cors=true
